//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenShop.DbOperationsDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbBill_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbBill_Items()
        {
            this.TbBillsItemsBridges = new HashSet<TbBillsItemsBridge>();
        }
    
        public long ItemIDPK { get; set; }
        public decimal Price { get; set; }
        public int ItemID_FK { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime TodayItem { get; set; }
    
        public virtual TbItemType TbItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbBillsItemsBridge> TbBillsItemsBridges { get; set; }
    }
}
