//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenShop.DbOperationsDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbStock
    {
        public int Stock { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool State { get; set; }
    }
}
