//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenShop.DbOperationsDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbTreaderTransaction
    {
        public System.DateTime TransactionData { get; set; }
        public decimal IncomeMoney { get; set; }
        public decimal OutcomeMoney { get; set; }
        public decimal Total { get; set; }
        public Nullable<long> TransactionBillID { get; set; }
        public long TreaderID { get; set; }
    
        public virtual TbTreader TbTreader { get; set; }
    }
}
