//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenShop.DbOperationsDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbTreader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbTreader()
        {
            this.TbBills = new HashSet<TbBill>();
            this.TbTreaderTransactions = new HashSet<TbTreaderTransaction>();
        }
    
        public long TreaderID { get; set; }
        public string TreaderName { get; set; }
        public decimal Money { get; set; }
        public string TreaderMobileNumber { get; set; }
        public string TreaderAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbBill> TbBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbTreaderTransaction> TbTreaderTransactions { get; set; }
    }
}
